### ISSUE TITLE
[BUG] 更新插件时配置文件会自动添加重新添加默认配置

### ISSUE THREAD

**Issue by TATyKeFei** [ChengZhiMeow/MHDF-Tools#10]
每当更新插件版本时，下方关于事件操作的默认配置会被重新添加进配置文件

```
    playerJoin:
      # 事件
      # =========================================
      # 玩家加入服务器 玩家退出服务器 玩家切换世界 玩家聊天
      # 玩家死亡 玩家复活 玩家移动 玩家传送 玩家破坏方块
      # 玩家放置方块
      # =========================================
      event: 玩家加入服务器
      # 白名单世界
      # world:
      #  - "world"
      group:
        # 默认
        default:
          # 权重
          weight: 0
          # 操作
          action:
          - '[message]|&e主人早上好噢~'
```
